#!/usr/bin/env python3
"""Supplement missing common collocations to collocations.json."""
import json
from collections import OrderedDict

JSON_PATH = "platform/plugins/english_listening/assets/collocations.json"

with open(JSON_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

print(f"Existing: {len(data)} entries")

# --- New collocations to add ---
new_collocations = {
    # ===== NOUN collocations (verb + noun) =====
    # have + noun
    "have a conversation": {"type": "noun", "meaning": "进行对话"},
    "have a party": {"type": "noun", "meaning": "举办派对"},
    "have fun": {"type": "noun", "meaning": "玩得开心"},
    "have a problem": {"type": "noun", "meaning": "有问题"},
    "have a meeting": {"type": "noun", "meaning": "开会"},
    "have a baby": {"type": "noun", "meaning": "生孩子"},
    "have a cold": {"type": "noun", "meaning": "感冒"},
    "have a headache": {"type": "noun", "meaning": "头疼"},
    "have a dream": {"type": "noun", "meaning": "做梦"},
    "have a rest": {"type": "noun", "meaning": "休息"},
    "have a bath": {"type": "noun", "meaning": "洗澡"},
    "have a drink": {"type": "noun", "meaning": "喝一杯"},
    "have a meal": {"type": "noun", "meaning": "吃饭"},
    "have a seat": {"type": "noun", "meaning": "请坐"},
    "have a word with": {"type": "noun", "meaning": "和...说句话"},
    "have access to": {"type": "noun", "meaning": "有权使用"},
    "have an impact on": {"type": "noun", "meaning": "对...有影响"},
    "have an effect on": {"type": "noun", "meaning": "对...有影响"},
    "have a chance": {"type": "noun", "meaning": "有机会"},
    "have difficulty": {"type": "noun", "meaning": "有困难"},
    "have trouble": {"type": "noun", "meaning": "有麻烦"},
    "have no idea": {"type": "noun", "meaning": "不知道"},
    "have second thoughts": {"type": "noun", "meaning": "重新考虑"},
    "have a good time": {"type": "noun", "meaning": "玩得开心"},
    "have the right to": {"type": "noun", "meaning": "有权利"},

    # do + noun
    "do homework": {"type": "noun", "meaning": "做作业"},
    "do business": {"type": "noun", "meaning": "做生意"},
    "do research": {"type": "noun", "meaning": "做研究"},
    "do a favor": {"type": "noun", "meaning": "帮忙"},
    "do the dishes": {"type": "noun", "meaning": "洗碗"},
    "do the laundry": {"type": "noun", "meaning": "洗衣服"},
    "do the shopping": {"type": "noun", "meaning": "购物"},
    "do the cooking": {"type": "noun", "meaning": "做饭"},
    "do the cleaning": {"type": "noun", "meaning": "打扫"},
    "do your best": {"type": "noun", "meaning": "尽力而为"},
    "do harm": {"type": "noun", "meaning": "造成伤害"},
    "do damage": {"type": "noun", "meaning": "造成损害"},
    "do exercise": {"type": "noun", "meaning": "锻炼"},
    "do a good job": {"type": "noun", "meaning": "做得好"},
    "do the right thing": {"type": "noun", "meaning": "做正确的事"},

    # pay + noun
    "pay attention": {"type": "noun", "meaning": "注意"},
    "pay a visit": {"type": "noun", "meaning": "拜访"},
    "pay the price": {"type": "noun", "meaning": "付出代价"},
    "pay tribute": {"type": "noun", "meaning": "致敬"},
    "pay a compliment": {"type": "noun", "meaning": "称赞"},
    "pay the bill": {"type": "noun", "meaning": "付账单"},
    "pay a fine": {"type": "noun", "meaning": "付罚款"},
    "pay respect": {"type": "noun", "meaning": "表示敬意"},
    "pay interest": {"type": "noun", "meaning": "付利息"},
    "pay a deposit": {"type": "noun", "meaning": "付定金"},
    "pay cash": {"type": "noun", "meaning": "付现金"},
    "pay by credit card": {"type": "noun", "meaning": "用信用卡支付"},

    # catch + noun
    "catch a cold": {"type": "noun", "meaning": "感冒"},
    "catch a bus": {"type": "noun", "meaning": "赶公交"},
    "catch a train": {"type": "noun", "meaning": "赶火车"},
    "catch a flight": {"type": "noun", "meaning": "赶飞机"},
    "catch fire": {"type": "noun", "meaning": "着火"},
    "catch sight of": {"type": "noun", "meaning": "看见"},
    "catch someone's attention": {"type": "noun", "meaning": "引起某人注意"},
    "catch a glimpse of": {"type": "noun", "meaning": "瞥见"},
    "catch a thief": {"type": "noun", "meaning": "抓小偷"},
    "catch a disease": {"type": "noun", "meaning": "染病"},

    # keep + noun
    "keep a secret": {"type": "noun", "meaning": "保守秘密"},
    "keep a promise": {"type": "noun", "meaning": "遵守承诺"},
    "keep a diary": {"type": "noun", "meaning": "记日记"},
    "keep a record": {"type": "noun", "meaning": "做记录"},
    "keep a balance": {"type": "noun", "meaning": "保持平衡"},
    "keep an open mind": {"type": "noun", "meaning": "保持开放心态"},
    "keep control": {"type": "noun", "meaning": "保持控制"},
    "keep quiet": {"type": "noun", "meaning": "保持安静"},
    "keep calm": {"type": "noun", "meaning": "保持冷静"},
    "keep the change": {"type": "noun", "meaning": "不用找了"},

    # break + noun
    "break a record": {"type": "noun", "meaning": "打破纪录"},
    "break the law": {"type": "noun", "meaning": "违法"},
    "break the silence": {"type": "noun", "meaning": "打破沉默"},
    "break a promise": {"type": "noun", "meaning": "违背承诺"},
    "break the ice": {"type": "noun", "meaning": "打破僵局"},
    "break the rules": {"type": "noun", "meaning": "违反规则"},
    "break the habit": {"type": "noun", "meaning": "改掉习惯"},
    "break a leg": {"type": "noun", "meaning": "祝好运"},
    "break new ground": {"type": "noun", "meaning": "开辟新领域"},
    "break the news": {"type": "noun", "meaning": "透露消息"},

    # give + noun
    "give advice": {"type": "noun", "meaning": "给建议"},
    "give a speech": {"type": "noun", "meaning": "发表演讲"},
    "give permission": {"type": "noun", "meaning": "给予许可"},
    "give a presentation": {"type": "noun", "meaning": "做演示"},
    "give a warning": {"type": "noun", "meaning": "发出警告"},
    "give an example": {"type": "noun", "meaning": "举例"},
    "give a reason": {"type": "noun", "meaning": "给出理由"},
    "give birth": {"type": "noun", "meaning": "生孩子"},
    "give a hand": {"type": "noun", "meaning": "帮忙"},
    "give a lift": {"type": "noun", "meaning": "搭便车"},
    "give priority": {"type": "noun", "meaning": "优先考虑"},
    "give consent": {"type": "noun", "meaning": "给予同意"},
    "give a guarantee": {"type": "noun", "meaning": "提供保证"},
    "give evidence": {"type": "noun", "meaning": "提供证据"},
    "give instructions": {"type": "noun", "meaning": "给指示"},
    "give notice": {"type": "noun", "meaning": "通知"},
    "give rise to": {"type": "noun", "meaning": "引起"},

    # save + noun
    "save time": {"type": "noun", "meaning": "节省时间"},
    "save money": {"type": "noun", "meaning": "省钱"},
    "save energy": {"type": "noun", "meaning": "节约能源"},
    "save space": {"type": "noun", "meaning": "节省空间"},
    "save a life": {"type": "noun", "meaning": "救命"},
    "save the environment": {"type": "noun", "meaning": "保护环境"},
    "save the date": {"type": "noun", "meaning": "记住这个日期"},
    "save the trouble": {"type": "noun", "meaning": "省去麻烦"},

    # spend + noun
    "spend time": {"type": "noun", "meaning": "花时间"},
    "spend money": {"type": "noun", "meaning": "花钱"},
    "spend a fortune": {"type": "noun", "meaning": "花一大笔钱"},
    "spend the night": {"type": "noun", "meaning": "过夜"},
    "spend a lifetime": {"type": "noun", "meaning": "花一辈子"},
    "spend the weekend": {"type": "noun", "meaning": "度周末"},
    "spend the holiday": {"type": "noun", "meaning": "度假"},
    "spend a day": {"type": "noun", "meaning": "花一天时间"},

    # tell + noun
    "tell a story": {"type": "noun", "meaning": "讲故事"},
    "tell the truth": {"type": "noun", "meaning": "说实话"},
    "tell a lie": {"type": "noun", "meaning": "说谎"},
    "tell a joke": {"type": "noun", "meaning": "讲笑话"},
    "tell a secret": {"type": "noun", "meaning": "告诉秘密"},
    "tell the difference": {"type": "noun", "meaning": "说出区别"},
    "tell the time": {"type": "noun", "meaning": "看时间"},
    "tell a story": {"type": "noun", "meaning": "讲故事"},

    # ask + noun
    "ask a question": {"type": "noun", "meaning": "问问题"},
    "ask for help": {"type": "noun", "meaning": "求助"},
    "ask for advice": {"type": "noun", "meaning": "征求建议"},
    "ask for permission": {"type": "noun", "meaning": "请求许可"},
    "ask a favor": {"type": "noun", "meaning": "请求帮忙"},
    "ask for directions": {"type": "noun", "meaning": "问路"},
    "ask for forgiveness": {"type": "noun", "meaning": "请求原谅"},
    "ask the price": {"type": "noun", "meaning": "问价格"},
    "ask for a refund": {"type": "noun", "meaning": "要求退款"},
    "ask for an explanation": {"type": "noun", "meaning": "要求解释"},

    # change + noun
    "change your mind": {"type": "noun", "meaning": "改变主意"},
    "change the subject": {"type": "noun", "meaning": "转移话题"},
    "change the world": {"type": "noun", "meaning": "改变世界"},
    "change direction": {"type": "noun", "meaning": "改变方向"},
    "change the channel": {"type": "noun", "meaning": "换频道"},
    "change your tune": {"type": "noun", "meaning": "改变态度"},
    "change sides": {"type": "noun", "meaning": "改变立场"},
    "change hands": {"type": "noun", "meaning": "易手"},
    "change clothes": {"type": "noun", "meaning": "换衣服"},
    "change the date": {"type": "noun", "meaning": "改日期"},

    # draw + noun
    "draw attention": {"type": "noun", "meaning": "引起注意"},
    "draw a conclusion": {"type": "noun", "meaning": "得出结论"},
    "draw a line": {"type": "noun", "meaning": "画线；划界限"},
    "draw a picture": {"type": "noun", "meaning": "画画"},
    "draw a distinction": {"type": "noun", "meaning": "区分"},
    "draw a parallel": {"type": "noun", "meaning": "做类比"},
    "draw a comparison": {"type": "noun", "meaning": "做比较"},
    "draw a breath": {"type": "noun", "meaning": "吸一口气"},
    "draw a crowd": {"type": "noun", "meaning": "吸引人群"},
    "draw inspiration": {"type": "noun", "meaning": "汲取灵感"},

    # hold + noun
    "hold a meeting": {"type": "noun", "meaning": "开会"},
    "hold a conversation": {"type": "noun", "meaning": "进行对话"},
    "hold a grudge": {"type": "noun", "meaning": "怀恨在心"},
    "hold an election": {"type": "noun", "meaning": "举行选举"},
    "hold a competition": {"type": "noun", "meaning": "举办比赛"},
    "hold a press conference": {"type": "noun", "meaning": "举行新闻发布会"},
    "hold a ceremony": {"type": "noun", "meaning": "举行仪式"},
    "hold a position": {"type": "noun", "meaning": "担任职位"},
    "hold the line": {"type": "noun", "meaning": "别挂电话；坚守阵地"},
    "hold a record": {"type": "noun", "meaning": "保持纪录"},
    "hold hands": {"type": "noun", "meaning": "牵手"},
    "hold your breath": {"type": "noun", "meaning": "屏住呼吸"},
    "hold your tongue": {"type": "noun", "meaning": "闭嘴"},
    "hold your ground": {"type": "noun", "meaning": "坚守立场"},

    # raise + noun
    "raise a question": {"type": "noun", "meaning": "提出问题"},
    "raise money": {"type": "noun", "meaning": "筹款"},
    "raise awareness": {"type": "noun", "meaning": "提高意识"},
    "raise a family": {"type": "noun", "meaning": "养家"},
    "raise an objection": {"type": "noun", "meaning": "提出异议"},
    "raise your voice": {"type": "noun", "meaning": "提高嗓门"},
    "raise a concern": {"type": "noun", "meaning": "提出关切"},
    "raise the bar": {"type": "noun", "meaning": "提高标准"},
    "raise an issue": {"type": "noun", "meaning": "提出问题"},
    "raise a child": {"type": "noun", "meaning": "抚养孩子"},
    "raise the alarm": {"type": "noun", "meaning": "拉响警报"},
    "raise expectations": {"type": "noun", "meaning": "提高期望"},

    # set + noun
    "set a goal": {"type": "noun", "meaning": "设定目标"},
    "set an example": {"type": "noun", "meaning": "树立榜样"},
    "set a record": {"type": "noun", "meaning": "创造纪录"},
    "set a deadline": {"type": "noun", "meaning": "设定期限"},
    "set a standard": {"type": "noun", "meaning": "设定标准"},
    "set a trap": {"type": "noun", "meaning": "设陷阱"},
    "set a trend": {"type": "noun", "meaning": "引领潮流"},
    "set a precedent": {"type": "noun", "meaning": "开创先例"},
    "set a date": {"type": "noun", "meaning": "确定日期"},
    "set the table": {"type": "noun", "meaning": "摆桌子"},
    "set the scene": {"type": "noun", "meaning": "设置场景"},
    "set the pace": {"type": "noun", "meaning": "设定节奏"},
    "set the tone": {"type": "noun", "meaning": "定调子"},
    "set the stage": {"type": "noun", "meaning": "做好准备"},
    "set fire to": {"type": "noun", "meaning": "放火"},

    # lose + noun
    "lose weight": {"type": "noun", "meaning": "减肥"},
    "lose interest": {"type": "noun", "meaning": "失去兴趣"},
    "lose control": {"type": "noun", "meaning": "失去控制"},
    "lose your temper": {"type": "noun", "meaning": "发脾气"},
    "lose your way": {"type": "noun", "meaning": "迷路"},
    "lose your job": {"type": "noun", "meaning": "失业"},
    "lose your nerve": {"type": "noun", "meaning": "失去勇气"},
    "lose confidence": {"type": "noun", "meaning": "失去信心"},
    "lose patience": {"type": "noun", "meaning": "失去耐心"},
    "lose touch": {"type": "noun", "meaning": "失去联系"},
    "lose track of": {"type": "noun", "meaning": "忘记；跟不上"},
    "lose consciousness": {"type": "noun", "meaning": "失去意识"},
    "lose face": {"type": "noun", "meaning": "丢面子"},
    "lose hope": {"type": "noun", "meaning": "失去希望"},
    "lose sleep": {"type": "noun", "meaning": "失眠"},
    "lose count": {"type": "noun", "meaning": "数不清"},
    "lose the game": {"type": "noun", "meaning": "输掉比赛"},
    "lose a battle": {"type": "noun", "meaning": "输掉战斗"},

    # win + noun
    "win a prize": {"type": "noun", "meaning": "获奖"},
    "win an award": {"type": "noun", "meaning": "获奖"},
    "win a game": {"type": "noun", "meaning": "赢得比赛"},
    "win a medal": {"type": "noun", "meaning": "赢得奖牌"},
    "win the lottery": {"type": "noun", "meaning": "中彩票"},
    "win an election": {"type": "noun", "meaning": "赢得选举"},
    "win the race": {"type": "noun", "meaning": "赢得比赛"},
    "win a contract": {"type": "noun", "meaning": "赢得合同"},
    "win a battle": {"type": "noun", "meaning": "赢得战斗"},
    "win the war": {"type": "noun", "meaning": "赢得战争"},
    "win a scholarship": {"type": "noun", "meaning": "获得奖学金"},
    "win the championship": {"type": "noun", "meaning": "赢得冠军"},
    "win the trust": {"type": "noun", "meaning": "赢得信任"},
    "win the heart": {"type": "noun", "meaning": "赢得芳心"},
    "win the case": {"type": "noun", "meaning": "打赢官司"},
    "win a victory": {"type": "noun", "meaning": "赢得胜利"},

    # earn + noun
    "earn money": {"type": "noun", "meaning": "赚钱"},
    "earn a living": {"type": "noun", "meaning": "谋生"},
    "earn a reputation": {"type": "noun", "meaning": "赢得声誉"},
    "earn respect": {"type": "noun", "meaning": "赢得尊重"},
    "earn a degree": {"type": "noun", "meaning": "获得学位"},
    "earn a salary": {"type": "noun", "meaning": "挣工资"},
    "earn a profit": {"type": "noun", "meaning": "获得利润"},
    "earn trust": {"type": "noun", "meaning": "赢得信任"},
    "earn a promotion": {"type": "noun", "meaning": "获得晋升"},
    "earn a place": {"type": "noun", "meaning": "赢得一席之地"},

    # gain + noun
    "gain experience": {"type": "noun", "meaning": "获得经验"},
    "gain access": {"type": "noun", "meaning": "获得访问权限"},
    "gain weight": {"type": "noun", "meaning": "增重"},
    "gain knowledge": {"type": "noun", "meaning": "获得知识"},
    "gain control": {"type": "noun", "meaning": "获得控制"},
    "gain a competitive advantage": {"type": "noun", "meaning": "获得竞争优势"},
    "gain insight": {"type": "noun", "meaning": "获得洞察"},
    "gain popularity": {"type": "noun", "meaning": "获得人气"},
    "gain support": {"type": "noun", "meaning": "获得支持"},
    "gain confidence": {"type": "noun", "meaning": "获得信心"},
    "gain recognition": {"type": "noun", "meaning": "获得认可"},
    "gain an understanding": {"type": "noun", "meaning": "获得理解"},

    # reach + noun
    "reach a decision": {"type": "noun", "meaning": "做出决定"},
    "reach an agreement": {"type": "noun", "meaning": "达成协议"},
    "reach a compromise": {"type": "noun", "meaning": "达成妥协"},
    "reach a conclusion": {"type": "noun", "meaning": "得出结论"},
    "reach a consensus": {"type": "noun", "meaning": "达成共识"},
    "reach a goal": {"type": "noun", "meaning": "达成目标"},
    "reach a peak": {"type": "noun", "meaning": "达到顶峰"},
    "reach a milestone": {"type": "noun", "meaning": "达到里程碑"},
    "reach a settlement": {"type": "noun", "meaning": "达成和解"},
    "reach a verdict": {"type": "noun", "meaning": "做出裁决"},
    "reach the top": {"type": "noun", "meaning": "到达顶峰"},
    "reach the age of": {"type": "noun", "meaning": "达到...年龄"},
    "reach a dead end": {"type": "noun", "meaning": "走进死胡同"},
    "reach out": {"type": "noun", "meaning": "伸出援手；联系"},

    # play + noun
    "play a role": {"type": "noun", "meaning": "扮演角色；起作用"},
    "play a part": {"type": "noun", "meaning": "起作用；扮演角色"},
    "play a game": {"type": "noun", "meaning": "玩游戏"},
    "play a trick": {"type": "noun", "meaning": "耍花招"},
    "play a joke": {"type": "noun", "meaning": "开玩笑"},
    "play an instrument": {"type": "noun", "meaning": "演奏乐器"},
    "play music": {"type": "noun", "meaning": "播放音乐"},
    "play sports": {"type": "noun", "meaning": "做运动"},
    "play a key role": {"type": "noun", "meaning": "起关键作用"},
    "play a major role": {"type": "noun", "meaning": "起重要作用"},
    "play a significant role": {"type": "noun", "meaning": "起重要作用"},
    "play a vital role": {"type": "noun", "meaning": "起至关重要作用"},

    # meet + noun
    "meet a deadline": {"type": "noun", "meaning": "赶上截止日期"},
    "meet the needs": {"type": "noun", "meaning": "满足需求"},
    "meet the requirements": {"type": "noun", "meaning": "满足要求"},
    "meet the standards": {"type": "noun", "meaning": "达到标准"},
    "meet the criteria": {"type": "noun", "meaning": "符合标准"},
    "meet expectations": {"type": "noun", "meaning": "满足期望"},
    "meet a challenge": {"type": "noun", "meaning": "面对挑战"},
    "meet the demand": {"type": "noun", "meaning": "满足需求"},
    "meet the target": {"type": "noun", "meaning": "达到目标"},
    "meet the conditions": {"type": "noun", "meaning": "满足条件"},
    "meet someone halfway": {"type": "noun", "meaning": "妥协；让步"},
    "meet with approval": {"type": "noun", "meaning": "获得批准"},
    "meet with resistance": {"type": "noun", "meaning": "遇到阻力"},
    "meet the cost": {"type": "noun", "meaning": "支付费用"},
    "meet the deadline": {"type": "noun", "meaning": "在截止日期前完成"},

    # face + noun
    "face a challenge": {"type": "noun", "meaning": "面对挑战"},
    "face the facts": {"type": "noun", "meaning": "面对事实"},
    "face a problem": {"type": "noun", "meaning": "面对问题"},
    "face the music": {"type": "noun", "meaning": "承担后果"},
    "face a dilemma": {"type": "noun", "meaning": "面临两难"},
    "face a crisis": {"type": "noun", "meaning": "面对危机"},
    "face the consequences": {"type": "noun", "meaning": "面对后果"},
    "face the truth": {"type": "noun", "meaning": "面对真相"},
    "face a difficulty": {"type": "noun", "meaning": "面对困难"},
    "face a threat": {"type": "noun", "meaning": "面对威胁"},
    "face an obstacle": {"type": "noun", "meaning": "面对障碍"},
    "face the future": {"type": "noun", "meaning": "面对未来"},
    "face a shortage": {"type": "noun", "meaning": "面临短缺"},
    "face an uncertain future": {"type": "noun", "meaning": "面对不确定的未来"},

    # solve + noun
    "solve a problem": {"type": "noun", "meaning": "解决问题"},
    "solve a mystery": {"type": "noun", "meaning": "解开谜团"},
    "solve a puzzle": {"type": "noun", "meaning": "解谜"},
    "solve a crime": {"type": "noun", "meaning": "破案"},
    "solve an equation": {"type": "noun", "meaning": "解方程"},
    "solve a dispute": {"type": "noun", "meaning": "解决争端"},
    "solve a riddle": {"type": "noun", "meaning": "解谜"},
    "solve a conflict": {"type": "noun", "meaning": "解决冲突"},
    "solve the issue": {"type": "noun", "meaning": "解决问题"},
    "solve the crisis": {"type": "noun", "meaning": "解决危机"},
    "solve a case": {"type": "noun", "meaning": "破案"},

    # ===== PREPOSITIONAL PHRASES =====
    "in charge of": {"type": "prepositional", "meaning": "负责"},
    "in favor of": {"type": "prepositional", "meaning": "支持；有利于"},
    "in terms of": {"type": "prepositional", "meaning": "就...而言"},
    "in spite of": {"type": "prepositional", "meaning": "尽管"},
    "in case of": {"type": "prepositional", "meaning": "万一"},
    "in addition to": {"type": "prepositional", "meaning": "除...之外"},
    "in relation to": {"type": "prepositional", "meaning": "关于；与...相关"},
    "in response to": {"type": "prepositional", "meaning": "作为对...的回应"},
    "in contrast to": {"type": "prepositional", "meaning": "与...对比"},
    "in comparison with": {"type": "prepositional", "meaning": "与...相比"},
    "in connection with": {"type": "prepositional", "meaning": "与...有关"},
    "in accordance with": {"type": "prepositional", "meaning": "根据；按照"},
    "in line with": {"type": "prepositional", "meaning": "符合；与...一致"},
    "in keeping with": {"type": "prepositional", "meaning": "与...一致"},
    "in exchange for": {"type": "prepositional", "meaning": "作为...的交换"},
    "in return for": {"type": "prepositional", "meaning": "作为...的回报"},
    "in need of": {"type": "prepositional", "meaning": "需要"},
    "in search of": {"type": "prepositional", "meaning": "寻找"},
    "in support of": {"type": "prepositional", "meaning": "支持"},
    "in pursuit of": {"type": "prepositional", "meaning": "追求"},
    "in honor of": {"type": "prepositional", "meaning": "向...致敬"},
    "in memory of": {"type": "prepositional", "meaning": "纪念"},
    "in recognition of": {"type": "prepositional", "meaning": "表彰"},
    "in the process of": {"type": "prepositional", "meaning": "在...过程中"},
    "in the middle of": {"type": "prepositional", "meaning": "在...中间"},
    "in the absence of": {"type": "prepositional", "meaning": "在...缺席的情况下"},
    "in the presence of": {"type": "prepositional", "meaning": "在...面前"},
    "in the event of": {"type": "prepositional", "meaning": "如果...发生"},
    "in the face of": {"type": "prepositional", "meaning": "面对"},
    "in the wake of": {"type": "prepositional", "meaning": "在...之后"},

    "on behalf of": {"type": "prepositional", "meaning": "代表"},
    "on the basis of": {"type": "prepositional", "meaning": "基于"},
    "on account of": {"type": "prepositional", "meaning": "由于"},
    "on top of": {"type": "prepositional", "meaning": "在...之上；除...之外"},
    "on the verge of": {"type": "prepositional", "meaning": "濒临"},
    "on the brink of": {"type": "prepositional", "meaning": "在...边缘"},
    "on the point of": {"type": "prepositional", "meaning": "正要...的时候"},
    "on the grounds of": {"type": "prepositional", "meaning": "以...为由"},
    "on the strength of": {"type": "prepositional", "meaning": "凭借"},
    "on the part of": {"type": "prepositional", "meaning": "就...而言"},
    "on the side of": {"type": "prepositional", "meaning": "站在...一边"},
    "on the subject of": {"type": "prepositional", "meaning": "关于...的话题"},
    "on the matter of": {"type": "prepositional", "meaning": "关于...的问题"},
    "on the issue of": {"type": "prepositional", "meaning": "关于...的问题"},
    "on the occasion of": {"type": "prepositional", "meaning": "在...之际"},

    "by means of": {"type": "prepositional", "meaning": "通过...方式"},
    "by way of": {"type": "prepositional", "meaning": "经由；作为"},
    "by virtue of": {"type": "prepositional", "meaning": "凭借；由于"},
    "by reason of": {"type": "prepositional", "meaning": "由于"},
    "by dint of": {"type": "prepositional", "meaning": "凭借"},
    "by courtesy of": {"type": "prepositional", "meaning": "承蒙...提供"},
    "by order of": {"type": "prepositional", "meaning": "奉...之命"},

    "with regard to": {"type": "prepositional", "meaning": "关于"},
    "with respect to": {"type": "prepositional", "meaning": "关于；就...而言"},
    "with reference to": {"type": "prepositional", "meaning": "关于"},
    "with the exception of": {"type": "prepositional", "meaning": "除了...之外"},
    "with a view to": {"type": "prepositional", "meaning": "为了；着眼于"},
    "with the aim of": {"type": "prepositional", "meaning": "以...为目的"},
    "with the help of": {"type": "prepositional", "meaning": "在...的帮助下"},
    "with the intention of": {"type": "prepositional", "meaning": "以...为目的"},
    "with the approval of": {"type": "prepositional", "meaning": "经...批准"},
    "with the consent of": {"type": "prepositional", "meaning": "经...同意"},
    "with the support of": {"type": "prepositional", "meaning": "在...的支持下"},

    "as a result of": {"type": "prepositional", "meaning": "由于；作为...的结果"},
    "as well as": {"type": "prepositional", "meaning": "以及；和...一样"},
    "as opposed to": {"type": "prepositional", "meaning": "与...相反"},
    "as far as": {"type": "prepositional", "meaning": "就...而言"},
    "as regards": {"type": "prepositional", "meaning": "关于"},
    "as for": {"type": "prepositional", "meaning": "至于"},
    "as to": {"type": "prepositional", "meaning": "关于"},
    "as a consequence of": {"type": "prepositional", "meaning": "由于"},
    "as a means of": {"type": "prepositional", "meaning": "作为...的方式"},
    "as part of": {"type": "prepositional", "meaning": "作为...的一部分"},

    "at the expense of": {"type": "prepositional", "meaning": "以...为代价"},
    "at the risk of": {"type": "prepositional", "meaning": "冒着...的风险"},
    "at the cost of": {"type": "prepositional", "meaning": "以...为代价"},
    "at the request of": {"type": "prepositional", "meaning": "应...的要求"},
    "at the invitation of": {"type": "prepositional", "meaning": "应...的邀请"},
    "at the suggestion of": {"type": "prepositional", "meaning": "根据...的建议"},
    "at the end of": {"type": "prepositional", "meaning": "在...结束时"},
    "at the beginning of": {"type": "prepositional", "meaning": "在...开始时"},
    "at the top of": {"type": "prepositional", "meaning": "在...顶部"},
    "at the bottom of": {"type": "prepositional", "meaning": "在...底部"},
    "at the back of": {"type": "prepositional", "meaning": "在...后面"},
    "at the front of": {"type": "prepositional", "meaning": "在...前面"},
    "at the heart of": {"type": "prepositional", "meaning": "在...的核心"},
    "at the center of": {"type": "prepositional", "meaning": "在...的中心"},
    "at the mercy of": {"type": "prepositional", "meaning": "受...的支配"},
    "at the disposal of": {"type": "prepositional", "meaning": "供...使用"},

    "for the sake of": {"type": "prepositional", "meaning": "为了...的缘故"},
    "for lack of": {"type": "prepositional", "meaning": "由于缺乏"},
    "for fear of": {"type": "prepositional", "meaning": "因为害怕"},
    "for the purpose of": {"type": "prepositional", "meaning": "为了...的目的"},
    "for the benefit of": {"type": "prepositional", "meaning": "为了...的利益"},
    "for the good of": {"type": "prepositional", "meaning": "为了...的利益"},
    "for the protection of": {"type": "prepositional", "meaning": "为了保护"},

    "out of control": {"type": "prepositional", "meaning": "失控"},
    "out of reach": {"type": "prepositional", "meaning": "够不着"},
    "out of sight": {"type": "prepositional", "meaning": "看不见"},
    "out of order": {"type": "prepositional", "meaning": "出故障"},
    "out of date": {"type": "prepositional", "meaning": "过时"},
    "out of work": {"type": "prepositional", "meaning": "失业"},
    "out of breath": {"type": "prepositional", "meaning": "喘不过气"},
    "out of stock": {"type": "prepositional", "meaning": "缺货"},
    "out of the question": {"type": "prepositional", "meaning": "不可能"},
    "out of touch": {"type": "prepositional", "meaning": "失去联系"},
    "out of the blue": {"type": "prepositional", "meaning": "突然地"},
    "out of context": {"type": "prepositional", "meaning": "断章取义"},
    "out of bounds": {"type": "prepositional", "meaning": "越界"},
    "out of character": {"type": "prepositional", "meaning": "不符合性格"},
    "out of focus": {"type": "prepositional", "meaning": "失焦；模糊"},
    "out of proportion": {"type": "prepositional", "meaning": "不成比例"},
    "out of sync": {"type": "prepositional", "meaning": "不同步"},
    "out of the ordinary": {"type": "prepositional", "meaning": "不寻常"},
    "out of the loop": {"type": "prepositional", "meaning": "不知情"},
    "out of the woods": {"type": "prepositional", "meaning": "脱离险境"},
    "out of the closet": {"type": "prepositional", "meaning": "出柜；公开"},

    # ===== ADVERB + ADJECTIVE collocations =====
    "highly likely": {"type": "adjective", "meaning": "极有可能"},
    "highly unlikely": {"type": "adjective", "meaning": "极不可能"},
    "highly successful": {"type": "adjective", "meaning": "非常成功"},
    "highly effective": {"type": "adjective", "meaning": "非常有效"},
    "highly recommend": {"type": "adjective", "meaning": "强烈推荐"},
    "highly competitive": {"type": "adjective", "meaning": "竞争激烈"},
    "highly controversial": {"type": "adjective", "meaning": "极具争议"},
    "highly qualified": {"type": "adjective", "meaning": "非常有资格"},
    "highly profitable": {"type": "adjective", "meaning": "高利润的"},
    "highly respected": {"type": "adjective", "meaning": "备受尊敬"},
    "highly sensitive": {"type": "adjective", "meaning": "高度敏感"},
    "highly skilled": {"type": "adjective", "meaning": "技术高超"},
    "highly sophisticated": {"type": "adjective", "meaning": "非常精密的"},
    "highly unlikely": {"type": "adjective", "meaning": "极不可能"},
    "highly unusual": {"type": "adjective", "meaning": "非常不寻常"},
    "highly visible": {"type": "adjective", "meaning": "非常显眼"},
    "highly valued": {"type": "adjective", "meaning": "非常受重视"},
    "highly dependent": {"type": "adjective", "meaning": "高度依赖"},
    "highly educated": {"type": "adjective", "meaning": "受过高等教育的"},
    "highly developed": {"type": "adjective", "meaning": "高度发达"},
    "highly desirable": {"type": "adjective", "meaning": "非常理想的"},
    "highly complex": {"type": "adjective", "meaning": "非常复杂"},
    "highly concentrated": {"type": "adjective", "meaning": "高度集中"},
    "highly classified": {"type": "adjective", "meaning": "高度机密"},
    "highly beneficial": {"type": "adjective", "meaning": "非常有益"},
    "highly advanced": {"type": "adjective", "meaning": "非常先进"},
    "highly accurate": {"type": "adjective", "meaning": "非常精确"},
    "highly accessible": {"type": "adjective", "meaning": "非常容易接近"},
    "highly acceptable": {"type": "adjective", "meaning": "非常可接受"},
    "highly accomplished": {"type": "adjective", "meaning": "非常有成就"},

    "deeply concerned": {"type": "adjective", "meaning": "深感担忧"},
    "deeply worried": {"type": "adjective", "meaning": "深感忧虑"},
    "deeply moved": {"type": "adjective", "meaning": "深受感动"},
    "deeply rooted": {"type": "adjective", "meaning": "根深蒂固"},
    "deeply committed": {"type": "adjective", "meaning": "深信不疑"},
    "deeply affected": {"type": "adjective", "meaning": "深受影响"},
    "deeply divided": {"type": "adjective", "meaning": "严重分裂"},
    "deeply embedded": {"type": "adjective", "meaning": "深深嵌入"},
    "deeply impressed": {"type": "adjective", "meaning": "印象深刻"},
    "deeply involved": {"type": "adjective", "meaning": "深度参与"},
    "deeply personal": {"type": "adjective", "meaning": "非常私人的"},
    "deeply religious": {"type": "adjective", "meaning": "非常虔诚的"},
    "deeply saddened": {"type": "adjective", "meaning": "深感悲痛"},
    "deeply satisfied": {"type": "adjective", "meaning": "非常满意"},
    "deeply shocked": {"type": "adjective", "meaning": "深感震惊"},
    "deeply suspicious": {"type": "adjective", "meaning": "深表怀疑"},
    "deeply troubled": {"type": "adjective", "meaning": "深感不安"},
    "deeply unpopular": {"type": "adjective", "meaning": "非常不受欢迎"},
    "deeply unsettling": {"type": "adjective", "meaning": "令人深感不安"},
    "deeply flawed": {"type": "adjective", "meaning": "有严重缺陷"},

    "bitterly cold": {"type": "adjective", "meaning": "严寒"},
    "bitterly disappointed": {"type": "adjective", "meaning": "极度失望"},
    "bitterly opposed": {"type": "adjective", "meaning": "强烈反对"},
    "bitterly divided": {"type": "adjective", "meaning": "严重分裂"},
    "bitterly resentful": {"type": "adjective", "meaning": "极度怨恨"},
    "bitterly ironic": {"type": "adjective", "meaning": "极具讽刺"},
    "bitterly contested": {"type": "adjective", "meaning": "激烈争夺"},
    "bitterly fought": {"type": "adjective", "meaning": "激烈战斗"},
    "bitterly criticized": {"type": "adjective", "meaning": "受到严厉批评"},
    "bitterly regretted": {"type": "adjective", "meaning": "深感后悔"},

    "fully aware": {"type": "adjective", "meaning": "充分意识到"},
    "fully prepared": {"type": "adjective", "meaning": "准备充分"},
    "fully equipped": {"type": "adjective", "meaning": "装备齐全"},
    "fully functional": {"type": "adjective", "meaning": "功能齐全"},
    "fully operational": {"type": "adjective", "meaning": "全面运作"},
    "fully committed": {"type": "adjective", "meaning": "全力以赴"},
    "fully integrated": {"type": "adjective", "meaning": "完全整合"},
    "fully automatic": {"type": "adjective", "meaning": "全自动"},
    "fully qualified": {"type": "adjective", "meaning": "完全合格"},
    "fully developed": {"type": "adjective", "meaning": "充分发展"},
    "fully furnished": {"type": "adjective", "meaning": "家具齐全"},
    "fully insured": {"type": "adjective", "meaning": "完全投保"},
    "fully licensed": {"type": "adjective", "meaning": "完全许可"},
    "fully recovered": {"type": "adjective", "meaning": "完全康复"},
    "fully satisfied": {"type": "adjective", "meaning": "完全满意"},
    "fully trained": {"type": "adjective", "meaning": "充分训练"},
    "fully compliant": {"type": "adjective", "meaning": "完全合规"},
    "fully accessible": {"type": "adjective", "meaning": "完全无障碍"},
    "fully accountable": {"type": "adjective", "meaning": "完全负责"},
    "fully adjustable": {"type": "adjective", "meaning": "完全可调"},

    "strongly opposed": {"type": "adjective", "meaning": "强烈反对"},
    "strongly recommend": {"type": "adjective", "meaning": "强烈建议"},
    "strongly influenced": {"type": "adjective", "meaning": "深受影响"},
    "strongly associated": {"type": "adjective", "meaning": "密切相关"},
    "strongly correlated": {"type": "adjective", "meaning": "强相关"},
    "strongly disagree": {"type": "adjective", "meaning": "强烈不同意"},
    "strongly agree": {"type": "adjective", "meaning": "强烈同意"},
    "strongly suggest": {"type": "adjective", "meaning": "强烈建议"},
    "strongly supported": {"type": "adjective", "meaning": "得到强烈支持"},
    "strongly criticized": {"type": "adjective", "meaning": "受到强烈批评"},
    "strongly committed": {"type": "adjective", "meaning": "坚定承诺"},
    "strongly motivated": {"type": "adjective", "meaning": "动力十足"},
    "strongly worded": {"type": "adjective", "meaning": "措辞强硬"},
    "strongly advised": {"type": "adjective", "meaning": "强烈建议"},
    "strongly attached": {"type": "adjective", "meaning": "深深依恋"},

    "widely used": {"type": "adjective", "meaning": "广泛使用"},
    "widely accepted": {"type": "adjective", "meaning": "广泛接受"},
    "widely known": {"type": "adjective", "meaning": "众所周知"},
    "widely available": {"type": "adjective", "meaning": "广泛可用"},
    "widely recognized": {"type": "adjective", "meaning": "被广泛认可"},
    "widely regarded": {"type": "adjective", "meaning": "被广泛认为"},
    "widely believed": {"type": "adjective", "meaning": "被广泛相信"},
    "widely distributed": {"type": "adjective", "meaning": "广泛分布"},
    "widely reported": {"type": "adjective", "meaning": "广泛报道"},
    "widely read": {"type": "adjective", "meaning": "广泛阅读"},
    "widely shared": {"type": "adjective", "meaning": "广泛分享"},
    "widely practiced": {"type": "adjective", "meaning": "广泛实行"},
    "widely adopted": {"type": "adjective", "meaning": "广泛采用"},
    "widely cited": {"type": "adjective", "meaning": "被广泛引用"},
    "widely anticipated": {"type": "adjective", "meaning": "被广泛期待"},
    "widely publicized": {"type": "adjective", "meaning": "被广泛宣传"},
    "widely praised": {"type": "adjective", "meaning": "广受赞誉"},
    "widely respected": {"type": "adjective", "meaning": "广受尊敬"},
    "widely condemned": {"type": "adjective", "meaning": "受到广泛谴责"},
    "widely discussed": {"type": "adjective", "meaning": "被广泛讨论"},

    "closely related": {"type": "adjective", "meaning": "密切相关"},
    "closely linked": {"type": "adjective", "meaning": "紧密相连"},
    "closely connected": {"type": "adjective", "meaning": "紧密相连"},
    "closely associated": {"type": "adjective", "meaning": "密切相关"},
    "closely monitored": {"type": "adjective", "meaning": "密切监控"},
    "closely watched": {"type": "adjective", "meaning": "密切关注"},
    "closely followed": {"type": "adjective", "meaning": "密切关注"},
    "closely resemble": {"type": "adjective", "meaning": "非常相似"},
    "closely guarded": {"type": "adjective", "meaning": "严密守卫"},
    "closely packed": {"type": "adjective", "meaning": "紧密排列"},
    "closely tied": {"type": "adjective", "meaning": "紧密相连"},
    "closely examined": {"type": "adjective", "meaning": "仔细检查"},
    "closely aligned": {"type": "adjective", "meaning": "高度一致"},
    "closely integrated": {"type": "adjective", "meaning": "紧密整合"},
    "closely held": {"type": "adjective", "meaning": "严密持有"},
    "closely supervised": {"type": "adjective", "meaning": "密切监督"},
    "closely contested": {"type": "adjective", "meaning": "激烈竞争"},
    "closely involved": {"type": "adjective", "meaning": "密切参与"},
    "closely observed": {"type": "adjective", "meaning": "密切观察"},
    "closely coordinated": {"type": "adjective", "meaning": "密切协调"},

    "heavily influenced": {"type": "adjective", "meaning": "深受影响"},
    "heavily reliant": {"type": "adjective", "meaning": "严重依赖"},
    "heavily armed": {"type": "adjective", "meaning": "全副武装"},
    "heavily guarded": {"type": "adjective", "meaning": "重兵把守"},
    "heavily criticized": {"type": "adjective", "meaning": "受到严厉批评"},
    "heavily populated": {"type": "adjective", "meaning": "人口密集"},
    "heavily regulated": {"type": "adjective", "meaning": "严格监管"},
    "heavily subsidized": {"type": "adjective", "meaning": "大量补贴"},
    "heavily invested": {"type": "adjective", "meaning": "大量投资"},
    "heavily damaged": {"type": "adjective", "meaning": "严重受损"},
    "heavily weighted": {"type": "adjective", "meaning": "权重很大"},
    "heavily accented": {"type": "adjective", "meaning": "口音很重"},
    "heavily forested": {"type": "adjective", "meaning": "森林茂密"},
    "heavily polluted": {"type": "adjective", "meaning": "严重污染"},
    "heavily dependent": {"type": "adjective", "meaning": "严重依赖"},
    "heavily involved": {"type": "adjective", "meaning": "重度参与"},
    "heavily armed": {"type": "adjective", "meaning": "全副武装"},
    "heavily fortified": {"type": "adjective", "meaning": "防御坚固"},
    "heavily laden": {"type": "adjective", "meaning": "满载"},
    "heavily pregnant": {"type": "adjective", "meaning": "怀孕晚期"},

    "acutely aware": {"type": "adjective", "meaning": "敏锐地意识到"},
    "painfully obvious": {"type": "adjective", "meaning": "显而易见"},
    "painfully slow": {"type": "adjective", "meaning": "极其缓慢"},
    "painfully shy": {"type": "adjective", "meaning": "极其害羞"},
    "painfully clear": {"type": "adjective", "meaning": "清楚得令人痛苦"},
    "painfully aware": {"type": "adjective", "meaning": "痛苦地意识到"},
    "painfully thin": {"type": "adjective", "meaning": "瘦得可怜"},
    "painfully honest": {"type": "adjective", "meaning": "诚实得令人痛苦"},

    "readily available": {"type": "adjective", "meaning": "随时可用"},
    "readily accessible": {"type": "adjective", "meaning": "容易获得"},
    "readily apparent": {"type": "adjective", "meaning": "显而易见"},
    "readily identifiable": {"type": "adjective", "meaning": "容易识别"},
    "readily understandable": {"type": "adjective", "meaning": "容易理解"},
    "readily visible": {"type": "adjective", "meaning": "显而易见"},
    "readily accepted": {"type": "adjective", "meaning": "容易接受"},
    "readily agreed": {"type": "adjective", "meaning": "欣然同意"},
    "readily admitted": {"type": "adjective", "meaning": "爽快承认"},
    "readily acknowledged": {"type": "adjective", "meaning": "欣然承认"},

    "vaguely familiar": {"type": "adjective", "meaning": "隐约熟悉"},
    "vaguely aware": {"type": "adjective", "meaning": "隐约意识到"},
    "vaguely reminiscent": {"type": "adjective", "meaning": "隐约让人想起"},
    "vaguely defined": {"type": "adjective", "meaning": "定义模糊"},
    "vaguely threatening": {"type": "adjective", "meaning": "隐隐约约的威胁"},
    "vaguely disappointed": {"type": "adjective", "meaning": "隐隐失望"},
    "vaguely uncomfortable": {"type": "adjective", "meaning": "隐隐不安"},
    "vaguely similar": {"type": "adjective", "meaning": "隐约相似"},
    "vaguely worded": {"type": "adjective", "meaning": "措辞含糊"},
    "vaguely understood": {"type": "adjective", "meaning": "理解模糊"},

    "perfectly normal": {"type": "adjective", "meaning": "完全正常"},
    "perfectly clear": {"type": "adjective", "meaning": "非常清楚"},
    "perfectly reasonable": {"type": "adjective", "meaning": "非常合理"},
    "perfectly legal": {"type": "adjective", "meaning": "完全合法"},
    "perfectly natural": {"type": "adjective", "meaning": "完全自然"},
    "perfectly capable": {"type": "adjective", "meaning": "完全有能力"},
    "perfectly safe": {"type": "adjective", "meaning": "完全安全"},
    "perfectly acceptable": {"type": "adjective", "meaning": "完全可以接受"},
    "perfectly valid": {"type": "adjective", "meaning": "完全有效"},
    "perfectly understandable": {"type": "adjective", "meaning": "完全可以理解"},
    "perfectly honest": {"type": "adjective", "meaning": "完全诚实"},
    "perfectly still": {"type": "adjective", "meaning": "完全静止"},
    "perfectly suited": {"type": "adjective", "meaning": "非常适合"},
    "perfectly balanced": {"type": "adjective", "meaning": "完美平衡"},
    "perfectly aligned": {"type": "adjective", "meaning": "完美对齐"},
    "perfectly happy": {"type": "adjective", "meaning": "非常快乐"},
    "perfectly innocent": {"type": "adjective", "meaning": "完全无辜"},
    "perfectly logical": {"type": "adjective", "meaning": "完全符合逻辑"},
    "perfectly good": {"type": "adjective", "meaning": "非常好的"},
    "perfectly fine": {"type": "adjective", "meaning": "完全没问题"},

    "relatively easy": {"type": "adjective", "meaning": "相对容易"},
    "relatively simple": {"type": "adjective", "meaning": "相对简单"},
    "relatively small": {"type": "adjective", "meaning": "相对较小"},
    "relatively low": {"type": "adjective", "meaning": "相对较低"},
    "relatively high": {"type": "adjective", "meaning": "相对较高"},
    "relatively stable": {"type": "adjective", "meaning": "相对稳定"},
    "relatively rare": {"type": "adjective", "meaning": "相对罕见"},
    "relatively short": {"type": "adjective", "meaning": "相对较短"},
    "relatively new": {"type": "adjective", "meaning": "相对较新"},
    "relatively recent": {"type": "adjective", "meaning": "相对较近"},
    "relatively minor": {"type": "adjective", "meaning": "相对较小"},
    "relatively modest": {"type": "adjective", "meaning": "相对适中"},
    "relatively cheap": {"type": "adjective", "meaning": "相对便宜"},
    "relatively unknown": {"type": "adjective", "meaning": "相对不知名"},
    "relatively unchanged": {"type": "adjective", "meaning": "相对不变"},
    "relatively narrow": {"type": "adjective", "meaning": "相对较窄"},
    "relatively mild": {"type": "adjective", "meaning": "相对温和"},
    "relatively inexpensive": {"type": "adjective", "meaning": "相对便宜"},
    "relatively common": {"type": "adjective", "meaning": "相对常见"},
    "relatively peaceful": {"type": "adjective", "meaning": "相对和平"},

    "increasingly important": {"type": "adjective", "meaning": "日益重要"},
    "increasingly popular": {"type": "adjective", "meaning": "日益流行"},
    "increasingly difficult": {"type": "adjective", "meaning": "日益困难"},
    "increasingly common": {"type": "adjective", "meaning": "日益普遍"},
    "increasingly complex": {"type": "adjective", "meaning": "日益复杂"},
    "increasingly concerned": {"type": "adjective", "meaning": "日益关注"},
    "increasingly aware": {"type": "adjective", "meaning": "日益意识到"},
    "increasingly frustrated": {"type": "adjective", "meaning": "日益沮丧"},
    "increasingly sophisticated": {"type": "adjective", "meaning": "日益精密"},
    "increasingly competitive": {"type": "adjective", "meaning": "日益竞争"},
    "increasingly urgent": {"type": "adjective", "meaning": "日益紧迫"},
    "increasingly dependent": {"type": "adjective", "meaning": "日益依赖"},
    "increasingly diverse": {"type": "adjective", "meaning": "日益多样化"},
    "increasingly isolated": {"type": "adjective", "meaning": "日益孤立"},
    "increasingly relevant": {"type": "adjective", "meaning": "日益相关"},
    "increasingly vocal": {"type": "adjective", "meaning": "日益直言不讳"},
    "increasingly influential": {"type": "adjective", "meaning": "日益有影响力"},
    "increasingly rare": {"type": "adjective", "meaning": "日益罕见"},
    "increasingly clear": {"type": "adjective", "meaning": "日益清楚"},
    "increasingly apparent": {"type": "adjective", "meaning": "日益明显"},

    "environmentally friendly": {"type": "adjective", "meaning": "环保的"},
    "socially acceptable": {"type": "adjective", "meaning": "社会可接受的"},
    "politically correct": {"type": "adjective", "meaning": "政治上正确的"},
    "economically viable": {"type": "adjective", "meaning": "经济上可行的"},
    "financially stable": {"type": "adjective", "meaning": "财政稳定的"},
    "technically feasible": {"type": "adjective", "meaning": "技术上可行的"},
    "scientifically proven": {"type": "adjective", "meaning": "经科学证明的"},
    "medically necessary": {"type": "adjective", "meaning": "医学上必要的"},
    "legally binding": {"type": "adjective", "meaning": "具有法律约束力的"},
    "morally wrong": {"type": "adjective", "meaning": "道德上错误的"},
    "ethically questionable": {"type": "adjective", "meaning": "伦理上有问题的"},
    "culturally diverse": {"type": "adjective", "meaning": "文化多元的"},
    "historically significant": {"type": "adjective", "meaning": "具有历史意义的"},
    "geographically isolated": {"type": "adjective", "meaning": "地理位置偏僻的"},
    "politically motivated": {"type": "adjective", "meaning": "出于政治动机的"},
    "strategically important": {"type": "adjective", "meaning": "战略上重要的"},
    "commercially available": {"type": "adjective", "meaning": "商业上可用的"},
    "genetically modified": {"type": "adjective", "meaning": "转基因的"},
    "psychologically damaging": {"type": "adjective", "meaning": "心理上伤害的"},
    "internationally recognized": {"type": "adjective", "meaning": "国际公认的"},

    # ===== ADDITIONAL PHRASAL VERBS =====
    "account for": {"type": "phrasalVerb", "meaning": "解释；占...比例"},
    "act on": {"type": "phrasalVerb", "meaning": "按照...行动"},
    "act up": {"type": "phrasalVerb", "meaning": "出毛病；调皮"},
    "add up": {"type": "phrasalVerb", "meaning": "加起来；说得通"},
    "add up to": {"type": "phrasalVerb", "meaning": "总计为"},
    "allow for": {"type": "phrasalVerb", "meaning": "考虑到"},
    "answer back": {"type": "phrasalVerb", "meaning": "顶嘴"},
    "answer for": {"type": "phrasalVerb", "meaning": "对...负责"},
    "back down": {"type": "phrasalVerb", "meaning": "让步；放弃"},
    "back off": {"type": "phrasalVerb", "meaning": "退后；放弃"},
    "back up": {"type": "phrasalVerb", "meaning": "支持；备份"},
    "bail out": {"type": "phrasalVerb", "meaning": "保释；救助"},
    "bank on": {"type": "phrasalVerb", "meaning": "指望"},
    "bear out": {"type": "phrasalVerb", "meaning": "证实"},
    "bear with": {"type": "phrasalVerb", "meaning": "耐心对待"},
    "blow up": {"type": "phrasalVerb", "meaning": "爆炸；放大"},
    "boil down to": {"type": "phrasalVerb", "meaning": "归结为"},
    "border on": {"type": "phrasalVerb", "meaning": "近乎"},
    "bow out": {"type": "phrasalVerb", "meaning": "退出"},
    "branch out": {"type": "phrasalVerb", "meaning": "拓展业务"},
    "brush off": {"type": "phrasalVerb", "meaning": "不理睬"},
    "brush up on": {"type": "phrasalVerb", "meaning": "复习；温习"},
    "bump into": {"type": "phrasalVerb", "meaning": "偶然遇见"},
    "burn out": {"type": "phrasalVerb", "meaning": "耗尽；烧坏"},
    "butt in": {"type": "phrasalVerb", "meaning": "插嘴"},
    "call back": {"type": "phrasalVerb", "meaning": "回电话"},
    "call on": {"type": "phrasalVerb", "meaning": "拜访；号召"},
    "call up": {"type": "phrasalVerb", "meaning": "打电话；征召"},
    "calm down": {"type": "phrasalVerb", "meaning": "冷静下来"},
    "care for": {"type": "phrasalVerb", "meaning": "照顾；喜欢"},
    "catch on": {"type": "phrasalVerb", "meaning": "理解；流行"},
    "catch up": {"type": "phrasalVerb", "meaning": "赶上"},
    "catch up with": {"type": "phrasalVerb", "meaning": "赶上；联系上"},
    "cheer up": {"type": "phrasalVerb", "meaning": "振作起来"},
    "chip in": {"type": "phrasalVerb", "meaning": "凑钱；插话"},
    "clean up": {"type": "phrasalVerb", "meaning": "清理干净"},
    "clear up": {"type": "phrasalVerb", "meaning": "清理；转晴"},
    "close down": {"type": "phrasalVerb", "meaning": "关闭"},
    "come about": {"type": "phrasalVerb", "meaning": "发生"},
    "come along": {"type": "phrasalVerb", "meaning": "一起来；进展"},
    "come around": {"type": "phrasalVerb", "meaning": "苏醒；改变主意"},
    "come down": {"type": "phrasalVerb", "meaning": "下来；下降"},
    "come down with": {"type": "phrasalVerb", "meaning": "染上病"},
    "come forward": {"type": "phrasalVerb", "meaning": "站出来"},
    "come off": {"type": "phrasalVerb", "meaning": "脱落；成功"},
    "come through": {"type": "phrasalVerb", "meaning": "渡过难关"},
    "count on": {"type": "phrasalVerb", "meaning": "指望；依靠"},
    "crack down on": {"type": "phrasalVerb", "meaning": "严厉打击"},
    "cross out": {"type": "phrasalVerb", "meaning": "划掉"},
    "cut back": {"type": "phrasalVerb", "meaning": "削减"},
    "cut down on": {"type": "phrasalVerb", "meaning": "减少"},
    "cut off": {"type": "phrasalVerb", "meaning": "切断；中断"},
    "cut out": {"type": "phrasalVerb", "meaning": "剪掉；戒掉"},
    "dawn on": {"type": "phrasalVerb", "meaning": "突然明白"},
    "die down": {"type": "phrasalVerb", "meaning": "逐渐平息"},
    "die out": {"type": "phrasalVerb", "meaning": "灭绝"},
    "dig up": {"type": "phrasalVerb", "meaning": "挖出；发现"},
    "do away with": {"type": "phrasalVerb", "meaning": "废除"},
    "do without": {"type": "phrasalVerb", "meaning": "没有...也行"},
    "drag on": {"type": "phrasalVerb", "meaning": "拖延"},
    "draw up": {"type": "phrasalVerb", "meaning": "起草；制定"},
    "dress up": {"type": "phrasalVerb", "meaning": "打扮"},
    "drop by": {"type": "phrasalVerb", "meaning": "顺道拜访"},
    "drop in": {"type": "phrasalVerb", "meaning": "顺便拜访"},
    "drop off": {"type": "phrasalVerb", "meaning": "让...下车；减少"},
    "drop out": {"type": "phrasalVerb", "meaning": "辍学；退出"},
    "dry up": {"type": "phrasalVerb", "meaning": "干涸；枯竭"},
    "dwell on": {"type": "phrasalVerb", "meaning": "纠结于"},
    "ease off": {"type": "phrasalVerb", "meaning": "减轻；放松"},
    "eat out": {"type": "phrasalVerb", "meaning": "外出吃饭"},
    "egg on": {"type": "phrasalVerb", "meaning": "怂恿"},
    "end up": {"type": "phrasalVerb", "meaning": "最终成为"},
    "face up to": {"type": "phrasalVerb", "meaning": "敢于面对"},
    "fall apart": {"type": "phrasalVerb", "meaning": "崩溃；散架"},
    "fall back